### ISSUE TITLE
Router Error on /login

### ISSUE THREAD

**Issue by Serubin** [klinker-apps/messenger-web#85]
This error occurs after login

```
Uncaught (in promise) 
NavigationDuplicated
message: "Navigating to current location ("/login") is not allowed"
name: "NavigationDuplicated"
_name: "NavigationDuplicated"
stack: "Error↵    at new NavigationDuplicated (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1975:14)↵    at HTML5History.confirmTransition (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2091:18)↵    at HTML5History.transitionTo (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2035:8)↵    at HTML5History.push (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2366:10)↵    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2780:22)↵    at new Promise (<anonymous>)↵    at VueRouter.push (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2779:12)↵    at VueComponent.beforeCreate (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js&:120:121)↵    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1862:57)↵    at callHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4216:7)"
__proto__: Error
```

**Comment by Serubin** [comment]
I should clarify, this is non-breaking. Just something that occurs.
